server:
  port: 8081

support.email: mycare@skytelservices.com

geo.ip.lib.enabled: false

purge.cron.expression: 0 0 5 * * ?

spring:

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mariadb://localhost:3306/pigeondb
    username: Pigeon
    password: PassWrd@11
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.mailhostbox.com
    port: 587
    username: mycare@skytelservices.com
    password: H(nGECReA6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false     
            